[package]
name = "momentum-models"
version = "0.1.0"
edition = "2024"

[dependencies]
candle-core = "0.9.1"
candle-nn = "0.9.1"
indicatif = "0.18.3"
linregress = "0.5.4"
rand = "0.9.2"
rand_distr = "0.5.1"
rayon = "1.11.0"
statrs = "0.17"
textplots = "0.8.7"
